server:
  port: 8080

  # 解决返回页面中文乱码问题
  servlet:
    encoding:
      force:true
      charset:UTF-8
# Spring
spring:
  application:
    # 应用名称
    name: websocket-web
  profiles:
    # 环境配置
    active: dev



